# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7d127cec495ef8dcc778b30991f0a46e129ec943868c2139c48cc155f28342ff8205aaa2e472fcb48f03b8802f3832a250100479cd2c0f24d5507d182fea324

test:
  secret_key_base: af779224167b8f93e7ceb583bea0b885216ef539d121bf06e9cb4a1436a24846f9b1cf2c2ed74e788e1a312fee7db179326e7abefa2501487fa140e5600e3826

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
